// Categorias oficiais do Rubra
// ATENÇÃO: NÃO alterar nem renomear estas listas.
// PF: 4 receitas / 10 despesas
// PJ: 31 receitas / 33 despesas na ordem exata original.

export const CATEGORIES_PJ: { income: string[]; expense: string[] } = {
  income: [
    'Consultas/US  dinheiro/cheque a vista/pix',
    'Consultas cartão crédito',
    'Consultas cartão de débito',
    'Cosultas/ US Cheques pré',
    'Pequenos procedimentos dinheiro/cheque',
    'Pequenos procedimentos Cartão de Crédito',
    'Pequenos procedimentos Cartão de débito',
    'Pequenos procedimentos Cheques pré',
    'Consultas de Convênio Unimed DR. EDSON',
    'Consultas de Convênio Unimed DR. WANDERSON',
    'Consulta Hap vida Dr. Wandersom',
    'Consulta Hap vida Dr. Dr. Edson',
    'Procedimento Unimed',
    'Procedimento Hap Vida',
    'Laboratório dinheiro',
    'Laboratório Cartão débito',
    'Laboratório Cartão de Crédito',
    'Laboratório Cheques à vista',
    'Laboratório Cheques pré',
    'Laboratoio Pix',
    'Centro Cirúrgico dinheiro/Pix',
    'Centro Cirúrgico cheque',
    'Centro Cirúrgico cartao debito',
    'Centro Cirúrgico cartão de crédito',
    'Centro Cirúrgico cheques pré',
    'Centro Cirúrgico convênio Hap Vida',
    'Centro Cirúrgico convênio Unimed',
    'Receitas totais Cirurgias Hospitais Externos particular',
    'Receitas totais Cirurgias Hospitais Externos HAP VIDA',
    'Receitas totais Cirurgias Hospitais Externos UNIMED',
    'Receita de Aluguel',
  ],
  expense: [
    'Custo dos Serviços Prestados (competência)',
    'Pagamento de Fornecedores (referência)',
    'Impostos sobre SERVIÇOS - ISS',
    'Impostos Federais (DARFs)',
    'Comissão dos cartões',
    'Comissão médicos terceiros DR. WANDERSON',
    'Comissão médicos terceiros',
    'Associação Comercial/crm/outros orgaos',
    'Correio/papelaria/grafica',
    'Higiene/limpeza/cozinha/copa',
    'Salários',
    '13 Salario',
    'Encargos Trabalhistas',
    'Encargos 13 Salario Provisionado',
    'Aluguel',
    'Iptu',
    'Prolabore',
    'Energia',
    'Telefone e internet',
    'Água',
    'Manutenção',
    'Aluguel consultorio Guaira',
    'Sistema de Informatica',
    'Contador',
    'Curso e Especializações',
    'Consultoria/Marketing',
    'Seguro',
    'Outros Fixos',
    'Outros Variaveis',
    'Financiamentos',
    'Empréstimos',
    'Juros / Antecipação',
    'Bens',
  ],
} as const

export const CATEGORIES_PF: { income: string[]; expense: string[] } = {
  income: ['APOSENTADORIA INSTITUTO', 'APOSENTADORIA INSS', 'OUTRAS RECEITAS', 'PROLABORE'],
  expense: [
    'CASA DA AVENIDA 3',
    'REFORMA',
    'FILHOS',
    'CASA DA AVENIDA 47',
    'CARROS E MOTOS',
    'CARTOES',
    'TAXA E JUROS BANCARIOS',
    'EMPRESTIMO',
    'INVESTIMENTO',
    'DESPESAS EXTRAS',
  ],
} as const
